version: '3.7'

services:
    mosquitto:
        image: eclipse-mosquitto
        hostname: mosquitto
        container_name: mosquitto
        restart: unless-stopped
        ports:
            - '1891:1891'
        volumes:
            - ./mosquitto:/etc/mosquitto
            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
